openapi: 3.0.0
info:
  version: 1.0.0
  title: Common Components
  description: Общие компоненты для всех микросервисов

paths: {}

components:
  schemas:
    username:
      type: string
      example: "user2"
      description: "Имя пользователя"
      
    password:
      type: string
      example: "qwerty"
      description: "Пароль пользователя"
      
    access_token:
      type: string
      example: "hwbefjvwbdf24wfyuihbk2"
      description: "JWT токен доступа"
      
    refresh_token:
      type: string
      example: "33nvdcaejfwhebf"
      description: "JWT токен обновления"
      
    email:
      type: string
      example: "qwerty@mail.ru"
      description: "Email адрес пользователя"
      
    expires_in:
      type: integer
      example: 600
      description: "Время жизни токена в секундах"
      
    error_message:
      type: string
      example: "bad request reason"
      description: "Сообщение об ошибке"
      
    pagination_limit:
      type: integer
      example: 100
      description: "Количество записей на странице"
      
    pagination_offset:
      type: integer
      example: 0
      description: "Смещение для пагинации"
      
    sensor_id:
      type: string
      example: "sensor-id-1"
      description: "Уникальный идентификатор датчика"
      
    sensor_value:
      type: string
      example: "22.5"
      description: "Значение с датчика"
      
    sensor_status:
      type: string
      example: "active"
      description: "Статус датчика"
      
    sensor_status_code:
      type: integer
      example: 2
      description: "Код статуса датчика (0-неактивен, 1-активен, 2-работает)"
      
    timestamp:
      type: string
      format: date-time
      example: "2025-01-01T00:00:00.123Z"
      description: "Временная метка в формате ISO 8601"
    
    sensor_data_item:
      type: object
      description: "Элемент данных с датчика"
      properties:
        value:
          $ref: "#/components/schemas/sensor_value"
        status:
          $ref: "#/components/schemas/sensor_status"
      
    sensor_update_request:
      type: object
      required:
        - id
        - value
        - status
        - ts
      properties:
        id:
          $ref: "#/components/schemas/sensor_id"
        value:
          $ref: "#/components/schemas/sensor_value"
        status:
          $ref: "#/components/schemas/sensor_status_code"
        ts:
          $ref: "#/components/schemas/timestamp"
      description: "Запрос на обновление данных датчика"

  securitySchemes:
    o2:
      type: http
      scheme: bearer
      bearerFormat: JWT
      description: "JWT Bearer токен для аутентификации"
    
    device_token:
      type: apiKey
      name: X-Device-Token
      in: header
      description: "API ключ для аутентификации устройств"
      
    device_key:
      type: apiKey
      name: X-Device-Key
      in: header
      description: "API ключ для аутентификации датчиков"

  responses:
    ok_response:
      description: Успешный запрос
      content:
        application/json:
          schema:
            type: object
            properties: {}
            
    bad_request_response:
      description: Ошибка в запросе
      content:
        application/json:
          schema:
            type: object
            properties:
              error:
                $ref: "#/components/schemas/error_message"
                
    internal_error_response:
      description: Ошибка на сервере
      content:
        application/json:
          schema:
            type: object
            properties:
              error:
                $ref: "#/components/schemas/error_message"
                
    unauthorized_response:
      description: Неавторизованный доступ
      content:
        application/json:
          schema:
            type: object
            properties:
              error:
                type: string
                example: "unauthorized access"
                
    forbidden_response:
      description: Доступ запрещен
      content:
        application/json:
          schema:
            type: object
            properties:
              error:
                type: string
                example: "access forbidden"

  parameters:
    limit_param:
      name: limit
      in: query
      required: false
      schema:
        $ref: "#/components/schemas/pagination_limit"
      description: "Количество записей на странице"
      
    offset_param:
      name: offset
      in: query
      required: false
      schema:
        $ref: "#/components/schemas/pagination_offset"
      description: "Смещение для пагинации"

